# Generated by Django 4.1.1 on 2022-10-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyprice',
            name='values',
            field=models.CharField(max_length=255),
        ),
    ]
