# Generated by Django 4.1.1 on 2022-10-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_energyprice_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyprice',
            old_name='values',
            new_name='SE1',
        ),
        migrations.AddField(
            model_name='energyprice',
            name='SE2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyprice',
            name='SE3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyprice',
            name='SE4',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
