# Generated by Django 4.1.1 on 2022-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
