# Generated by Django 4.1.1 on 2022-10-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnodeTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('expires_in', models.PositiveIntegerField()),
                ('scope', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=100)),
            ],
        ),
    ]
