# Generated by Django 4.1.1 on 2022-10-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enode', '0002_enodetokenmodel_expires_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enodetokenmodel',
            name='expires_in',
            field=models.PositiveIntegerField(),
        ),
    ]
